name: Trigger auto deployment for kafka-worker-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kafka-worker-container-AutoDeployTrigger-a65e0f0c-80dc-4c3f-bcad-4576e0ad5883.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KAFKAWORKERCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KAFKAWORKERCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KAFKAWORKERCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker Image
        run: |
          docker login hustleguardregistry.azurecr.io -u ${{ secrets.KAFKAWORKERCONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.KAFKAWORKERCONTAINER_REGISTRY_PASSWORD }}
          docker build -t hustleguardregistry.azurecr.io/kafka-worker-container:${{ github.sha }} -f ${{ github.workspace }}/backend/Dockerfile.worker ${{ github.workspace }}/backend
          docker push hustleguardregistry.azurecr.io/kafka-worker-container:${{ github.sha }}

      - name: Update Azure Container App
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kafka-worker-container -g HustleGuard --server hustleguardregistry.azurecr.io --username ${{ secrets.KAFKAWORKERCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.KAFKAWORKERCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n kafka-worker-container -g HustleGuard --container-name kafka-worker-container --image hustleguardregistry.azurecr.io/kafka-worker-container:${{ github.sha }}


